### ISSUE TITLE
(UX/UI) Refactor: Diseño de la vista Home

### ISSUE THREAD

**Issue by MatiasBidart** [Augustofrx/Celebria-App#7]
**Este es un Issue que hereda del padre #6** 
Rediseñar la vista **_Home_** de la apliación y sus componentes: "_Registra tu evento_" y "_Tus eventos_".

**Actualmente:**
![image](https://github.com/user-attachments/assets/878dca99-e9c4-4a05-9e77-eba25a881c9d)

Hacer más intuitivo para el usuario dónde tiene que clickear para crear su primer evento. Por ejemplo, muchas aplicaciones que se basan en un tipo de contenido creado por el usuario muestra un cartel "Oops! aun no hay nada creado, pulsa aquí para crear tu primer contenido". Podría usarse logotipos para hacer más atractiva la vista Home también. Ejemplos: 
![image](https://github.com/user-attachments/assets/8dccc510-bc87-4753-9139-ec11beeabe27)
![image](https://github.com/user-attachments/assets/d79e50a3-c109-49c2-95f8-f134bdb4f915)

**Comment by GiseOt** [comment]
El commit "(UX/UI) Refactor: Diseño de la vista Home"refactoriza la vista Home para mejorar el diseño y la experiencia del usuario. 
También se han implementado nuevos estilos para optimizar la presentación en móviles y escritorios.
